name: Pin with Pinata
description: Pin files using Pinata
branding:
  icon: upload-cloud
  color: green
inputs:
  cid:
    description: IPFS CID to publish
    required: true
  key:
    description: Pinata key
    required: true
  secret:
    description: Pinata secret
    required: true
outputs:
  name:
    description: IPNS name
runs:
  using: node16
  main: index.js
